// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = (require("events")).EventEmitter;

  (function(superClass) {
    extend(_Class, superClass);

    function _Class() {
      this.world = new World();
    }

    _Class.prototype.init = function() {};

    _Class.prototype.update = function(info) {};

    return _Class;

  })(EventEmitter);

}).call(this);
