// Generated by CoffeeScript 1.10.0
(function() {
  var code, codes, file, files, fs, i, len, path, targetFile, threeMathDir;

  fs = require("fs");

  path = require("path");

  threeMathDir = "./Threejs/src/math/";

  targetFile = "./common/threeMath.js";

  files = fs.readdirSync(threeMathDir);

  codes = [];

  for (i = 0, len = files.length; i < len; i++) {
    file = files[i];
    codes.push(fs.readFileSync(path.join(threeMathDir, file)).toString());
  }

  code = "THREE = {}\nexports.THREE = THREE;\n" + (codes.join(';\n'));

  fs.writeFileSync(targetFile, code);

}).call(this);
