// Generated by CoffeeScript 1.10.0
(function() {
  var SharedSettings;

  SharedSettings = {
    serverHost: "192.168.0.200",
    serverPort: 1223,
    frameRate: 60
  };

  exports.SharedSettings = SharedSettings;

}).call(this);
