// Generated by CoffeeScript 1.4.0
(function() {
  var SharedSettings;

  SharedSettings = {
    serverHost: "192.168.2.212",
    serverPort: 1223,
    frameRate: 60
  };

  exports.SharedSettings = SharedSettings;

}).call(this);
